name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  go_router: ^17.1.0
  google_fonts: ^8.0.2
  http: ^1.6.0
  intl: ^0.20.2
  textfield_search: ^0.11.1
  yandex_maps_mapkit_lite: ^4.33.1-beta

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/photo/